# .github/workflows/release.yml
name: Release

permissions:
  contents: write
  
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'semver bump (patch, minor, major)'
        required: true
        type: choice
        options: [patch, minor, major]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - id: bump
        run: |
          NEW=$(npm version ${{ github.event.inputs.release_type }} --no-git-tag-version)
          echo "ver=$NEW" >> $GITHUB_OUTPUT
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: release ${{ steps.bump.outputs.ver }} [skip ci]"
          git tag v${{ steps.bump.outputs.ver }}
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
