name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'semver bump (patch, minor, major)'
        required: true
        type: choice
        options: [patch, minor, major]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci

      - id: bump
        run: |
          NEW=$(npm version ${{ github.event.inputs.release_type }} --no-git-tag-version)
          echo "ver=$NEW" >> $GITHUB_OUTPUT

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore: release ${{ steps.bump.outputs.ver }} [skip ci]"

      - name: Check if tag already exists
        id: check_tag
        run: |
          git fetch --tags
          TAG_NAME=${{ steps.bump.outputs.ver }}
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git tag ${{ steps.bump.outputs.ver }}
          git push origin HEAD:release --tags

      - name: Set up .npmrc for publish
        run: |
          cat <<EOF > ~/.npmrc
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
